### ISSUE TITLE
might be using soft-f64

### ISSUE THREAD

**Issue by jordens** [quartiq/thermostat-eem#121]
thumbv7em-non-eabihf with target-cpu=cortex-m7 appears to select soft-f64 ops while eabi (non-hf) does select hw-f64 but is worse w.r.t. register stacking.

**Comment by jordens** [comment]
c.f. #56

**Comment by jordens** [comment]
https://github.com/quartiq/thermostat-eem/commit/14a4a0306d103199b9b7f3f19bfb044f0ffb2273

**Comment by chrisnc** [comment]
I believe https://github.com/rust-lang/rust/pull/123159 should solve this.
