### ISSUE TITLE
internal temperature sensor reads wrong values

### ISSUE THREAD

**Issue by nkrackow** [quartiq/thermostat-eem#16]
The internal temperature sensor on adc3 reads variable values depending on sampling rate. At very low rates the values read far to low. The stm32h7hal example coder reads plausible values at all rates.
For now parked [here](https://github.com/quartiq/thermostat-eem/tree/internal_adc_temp).

**Comment by jordens** [comment]
Since #21 and #47 this can probably be landed now. But not critical.

**Comment by jordens** [comment]
@nkrackow can this be closed?

**Comment by nkrackow** [comment]
Yes, since we closed https://github.com/quartiq/stabilizer/issues/585 too.
