### ISSUE TITLE
adc.max_sample() is (used) wrong

### ISSUE THREAD

**Issue by jordens** [quartiq/thermostat-eem#20]
https://github.com/stm32-rs/stm32h7xx-hal/blob/4ebb5c15d2ca97e66155cb6822426fa2e7aec746/src/adc.rs#L800

The `- 1` in there isn't correct when used to scale the code to obtain voltage.

**Comment by jordens** [comment]
https://github.com/stm32-rs/stm32h7xx-hal/pull/344 closed by https://github.com/stm32-rs/stm32h7xx-hal/pull/344 
scheduled for `stm32h7xx-hal` v0.12

**Comment by jordens** [comment]
@nkrackow I think we are using hal v0.12 now, right?

**Comment by nkrackow** [comment]
yes.
