### ISSUE TITLE
ADC communication probing

### ISSUE THREAD

**Issue by nkrackow** [quartiq/thermostat-eem#28]
I'll just collect a few observations of the ADC communication here.

Reading out all ADCs (that finish sampling at the same time) with our staggered interrupt routine and a 12.5 MHz SPI clock takes about 130 - 140 us. Blue is CS of the first ADC, which is low most of the time until it's data is read out and the other ADCs are selected. Yellow is the SPI dout signal, first going low to signal new data and trigger the interrupt and then giving back the data from the ADCs.
![Screenshot from 2022-04-08 17-59-53](https://user-images.githubusercontent.com/17088194/162492262-a51f26b3-e211-4ebe-b55f-3de54427344e.png)

**Comment by jordens** [comment]
Reason for the long time between reads?

**Comment by nkrackow** [comment]
No, that is `--debug`. Good point.

**Comment by nkrackow** [comment]
![Screenshot from 2022-04-11 11-05-05](https://user-images.githubusercontent.com/17088194/162703732-10b966f7-1427-4ea7-b950-2ad6ba955031.png)
Here you can see that the next ADC that is selected immediately pulls dout low, triggering the interrupt. But then it takes quite a long time for the CPU to handle it. I think it actually fully completes the last interrupt with all the prints before handling the next. I'll look into how to use rtic such that a new interrupt can interrupt the currently running one.

The other thing is that it takes about 2 us for the CPU to deselect the current ADC and then 4 us to look up which ADC comes next and select it. This is `--debug`. With `--release` things are a bit faster (I think mostly the prints) but the same behavior.

**Comment by jordens** [comment]
You are likely just measuring the speed of formatting.

**Comment by nkrackow** [comment]
Ok, so it is not possible with rtic to pre-empt a hardware interrupt task with itself. But I don't think that's a problem. It's not like things could go wrong here when each interrupt is first completed while the new has already triggered. And we also don't gain any savings in CPU time since we have to perform the same operations either way.

**Comment by nkrackow** [comment]
![Screenshot from 2022-04-11 13-40-45](https://user-images.githubusercontent.com/17088194/162733156-16294379-fffa-4a4e-8f1d-873df129f52c.png)
With `--release` and no prints things are very fast now. Also I have seen that every reading cycle looks exactly the same without any timing jitter if I give the isr a higher priority than other tasks. If it is the same there is some jitter.

**Comment by jordens** [comment]
As mentioned before, the next interrupt will just pend and chain right away.
