### ISSUE TITLE
FW v0.1 measurements

### ISSUE THREAD

**Issue by nkrackow** [quartiq/thermostat-eem#38]
- [x] For 10K ref in the middle (channel 3 or 4) determine if PWM/TEC output on all out channels makes a difference (determine max effect)
- [x] good data of 10K ref 1 kHz ADC samples (integers) -> log spectrum 
   - [x] standard config (1M samples)
   - [x] single ended (Ain- - REF-) performance (same HW, just different ADC config, 1M samples)
   - [x] with long cable (10k samples)
- [x] absolute difference of 10K with/without cable 
- [x] transfer function from NTC to TEC (determine V(adc) to I(TEC) coefficient as calibration)
- [x] common mode rejection. inject into shorted NTC input. hack code to bypass temperature measurement (to get a reliable V(adc) to I(TEC) conversion coefficient as calibration)
- [x] TEC output voltage noise spectrum with TEC connected and driven, constant current, Measure relative to gnd (thus measuring 1/2 differential + common mode). (500 kHz vs. 1 MHz switchable with gpio in FW)
- [x] probe and disturb around the board (determine max effect)
- [x] investigate header board temperature susceptibility (vs DMM, ref 10k vs ref 5k, locate sensitive location/component)

**Comment by nkrackow** [comment]
## 10K ref data

### Setup
- [Vishay 10K reference resistor](https://www.digikey.de/de/products/detail/vishay-foil-resistors-division-of-vishay-precision-group/Y145310K0000V9L/2609894) 
- ADC output data rate set to 1007 Hz -> 503.5 Hz sample rate per Thermostat channel, 50% of time sampling each channel.
- Sinc5Sinc1 ADC filter, no postfilter.
- Room temperature headerboard directly connected to Thermostat, 10K REF leads directly in Molex campling connector block.

### Data
[raw.zip](https://github.com/quartiq/thermostat-eem/files/8699736/raw.zip)
![standard_10K](https://user-images.githubusercontent.com/17088194/168586065-115141aa-43f3-46df-b1d4-2fedf1837477.png)

### Analysis
- Standard deviation over full bandwidth (250 Hz): 9.679 LSB, 51.4368 uK
- RMS noise 0.01 Hz - 1 Hz: 0.6323 LSB/Hz,  3.3601 uK/Hz

**Comment by jordens** [comment]
@nkrackow do keep an eye on https://github.com/sinara-hw/Thermostat/issues/46 and compare

**Comment by nkrackow** [comment]
## 10K ref with cable

### Setup
- [Vishay 10K reference resistor](https://www.digikey.de/de/products/detail/vishay-foil-resistors-division-of-vishay-precision-group/Y145310K0000V9L/2609894) 
- ADC output data rate set to 1007 Hz -> 503.5 Hz sample rate per Thermostat channel, 50% of time sampling each channel.
- Sinc5Sinc1 ADC filter, no postfilter.
- Room temperature headerboard onnected to Thermostat **via a ~0.5 m 24 AWG D-SUB cable**, 10K REF leads directly in Molex campling connector block.

### Data
[raw_cable.txt](https://github.com/quartiq/thermostat-eem/files/8700086/raw_cable.txt)
![cable_10K](https://user-images.githubusercontent.com/17088194/168594791-70da6b02-da0f-4145-8966-2c185487a7ab.png)

### Analysis
- Standard deviation over full bandwidth (250 Hz): 9.584 LSB, 50.9279 uK
- RMS noise 0.01 Hz - 1 Hz: 0.6199 LSB,  3.2943 uK
- Mean value difference to 10K ref without cable: +16.8 LSB

**Comment by jordens** [comment]
Note to self: two channels: the noise bandwidth is 500 Hz

**Comment by nkrackow** [comment]
## TEC output crosstalk

There is a slight, likely thermal effect of the TEC output back to the adc channels. Same settings as with "10K ref data", 3A TEC current when enabled. TEC output channel 3 traces seems to be the closest to all of the adc inputs on the layout.

### Input channel 5, output channel 3, headboard directly at Thermostat:
![output_drive](https://user-images.githubusercontent.com/17088194/168635454-71e3b6e0-f678-4605-9e1c-3a6a43dd80d6.png)

### Input channel 3, output channel 3, headboard directly at Thermostat:
![output_drive_2](https://user-images.githubusercontent.com/17088194/168635858-b932bea7-d800-42c4-8cca-ce280bd65d34.png)

### Input channel 3, output channel 3, ~0.5 m cable to Thermostat:
![output_drive_cable](https://user-images.githubusercontent.com/17088194/168637107-c2a68537-6eb5-4fda-a607-6036d526d130.png)

**Comment by jordens** [comment]
How large is it?

**Comment by nkrackow** [comment]
> How large is it?
I annotated it in the comment.

**Comment by nkrackow** [comment]
## Thermal disturbance of the boards

The following data was taken under the same conditions again. At three times I heated up some part of the boards with a hot air station.The times of disturbance are annotated and the corresponding thermal image and maximum deviation is shown below. DIfference is with respect to the start of the time series.
![download](https://user-images.githubusercontent.com/17088194/168774744-1a1050fd-4648-4eb4-9560-86f820a26ec1.png)

### Base image of the board sampling data on all channels, all outputs disabled
![FLIR0150](https://user-images.githubusercontent.com/17088194/168775199-c272d579-23ad-47a1-8616-6d40d5eb4351.jpg)

### [1] ADCs and surrounding circuitry to about 120 °C
![FLIR0154](https://user-images.githubusercontent.com/17088194/168775231-12404f89-8c9f-4f33-8410-41992b9a793d.jpg)
Max. deviation: 350 LSB

### [2] D-SUB connector on the board side to about 120 °C
![FLIR0158](https://user-images.githubusercontent.com/17088194/168775435-69d9c623-7901-4150-92c9-d13e19d53fbb.jpg)
Max. deviation:  -80 LSB

### [3] Headboard bottom side where the reference resistors are located to about 120 °C
ambient (before disturbance):
![FLIR0158](https://user-images.githubusercontent.com/17088194/168775753-9f74787b-3243-4eeb-8c87-f2b2f47f6f22.jpg)
heated:
![FLIR0159](https://user-images.githubusercontent.com/17088194/168775736-3c452f70-6b7d-473d-81be-5f786899216e.jpg)
Max. deviation: 570 LSB

**Comment by nkrackow** [comment]
## Aspirate onto the bottom of the headboard

By far the biggest disturbance I noticed is by aspirating onto the bottom of the headboard such that a little moisture condensates on the board. It is visible as tiny droplets (usual condensation) but those were difficult to photograph. The board temperature only changes by about 2 °C. 

I have aspirated only about the first 15% of the disturbance in the data. Then the deviations stays roughly constant until it rapidly goes back to the initial value. This is consistent with visibility of condensation on the board.

![aspirate](https://user-images.githubusercontent.com/17088194/168784356-ca373d8b-147f-4fdd-a303-77d8e794e690.png)
Max. deviation: 3440 LSB, about 0.02 °C

**Comment by nkrackow** [comment]
##  Frequency response

For the frequency response and group delay measurements the temperature conversion step was substituted by just a constant conversion coefficient so that the input-output relation is linear over the full scale. All the other processing like IIR and current to dac_code conversion are still present. The group delay should therefore not be significantly effected since much of it is in the ADC/DAC.

The following frequency magnitude responses measurements were done with a 2 V peak to peak, 2.5 V offset stimulation between the positive differential ADC input and the negative reference. The negative ADC input is still pulled to the negative reference by a 5K reference resistor on the headboard. The output was taken over a 1 ohm load resistor connected at the TEC output. The IIR only had the first b coefficient ("proportional gain") set to a value such that the output is between about 0.3 and 0.8 A. First input channel (ADC0 ch 0) and first output channel were used.

### Setup
![d4abf54e-db15-4a1c-8418-6b5a7e6e5eb7](https://user-images.githubusercontent.com/17088194/169259784-9aafee4e-b0af-40a4-a66d-4157ca1c9dde.jpg)

### Frequency response 
![1kHz_spec](https://user-images.githubusercontent.com/17088194/169257568-80300b4e-c8c9-4482-97f8-effa2ff23f8f.png)
![Screenshot from 2022-05-19 11-06-23](https://user-images.githubusercontent.com/17088194/169257651-9e44c96a-e572-4062-9a3b-d35b916f3b35.png)
First plot is from HP89410A with 100x averaging, second from an Analog Discovery. The ADC first order CIC response (with 1007 Hz effective rate) can clearly be seen. Since only half the samples go to each ADC channel, the nyquist rate for one channel is about 250 Hz. In the analog discovery plot (wich is not averaged) you can see some beating effects around the nyquist rate.


### Group delay
![group_delay](https://user-images.githubusercontent.com/17088194/169262468-b4565942-3f75-4113-8ac9-200ae2e18a7b.png)
Group delay is about 3.2 ms.

**Comment by nkrackow** [comment]
## TEC driver output spectrum
![1MHz_spec](https://user-images.githubusercontent.com/17088194/169263149-2c22ef57-9660-498d-afa1-1217911d28ee.png)
The driver switching frequency can be seen at bout 580 kHz.

**Comment by nkrackow** [comment]
## DAC time constant
![Screenshot from 2022-05-19 10-39-40](https://user-images.githubusercontent.com/17088194/169263645-c28904be-9d1c-4b87-8903-1c2bd2c99b2d.png)
Output time constant is about 210 us. The 1000 kHz lowpass installed between DAC and TEC driver should have about 160 us.

**Comment by jordens** [comment]
The analog discovery has a differential input with floating shield?
Ans why is the second lobe now -23 dB? Is that understood from the filter/decimation chains?
Some quantitative numbers would be useful. It's ok if they have a errorbar (then estimate that errorbar).

* TEC current thermal crosstalk magnitude (LSB/K)
* TEC current direct crosstalk (or upper limit if not detected)
* output ripple (A pk-pk worst case)
* output 580 kHz amplitude (A pk-pk worst case)
* a reasonable magnitude of the tempco of the board (LSB/K)
* Common mode voltage ripple (or upper limit)

**Comment by nkrackow** [comment]
> The analog discovery has a differential input with floating shield? 

Differental yes, floating no. You can measure up to 50 V wrt. ground differentially.

>Ans why is the second lobe now -23 dB? Is that understood from the filter/decimation chains? 

I think it was the same yesterday. Also the one plot is from yesterday and there it is about that too.

>Some quantitative numbers would be useful. It's ok if they have a errorbar (then estimate that errorbar).
> 
> * TEC current thermal crosstalk magnitude (LSB/K)

For which channel/configuration is that? Just the one channel that I suspect to be the most effected? Should I assume linear correspondence between temperature of the TEC driver chip and the output deviation?

> * TEC current direct crosstalk (or upper limit if not detected)

TODO.

> * output ripple (A pk-pk worst case)

I am not capable of determining this accurately. I see significant switching noise at about 68 kHz which must come from some power supply here somewhere. I tried many different ways of grounding but I can not get rid of it. I know that it is not trivial to accurately measure power supply ripple. This is with 3A output. The switching noise is also there when the output is off.
![Screenshot from 2022-05-19 15-00-24](https://user-images.githubusercontent.com/17088194/169300338-76714e49-f34c-48ca-9680-8b0a58e36c02.png)

If I try to look through this switching noise this looks like below 10 mApp noise. 
![Screenshot from 2022-05-19 15-32-06](https://user-images.githubusercontent.com/17088194/169306469-1b5a30b9-c716-47e5-9b81-59baaf9713a2.png)


> * output 580 kHz amplitude (A pk-pk worst case)

About 200 uApp right at this frequency. Too small to see in the time domain. The y scale in the spectrum is in absolute V peak to peak (with a 1 ohm load).

![Screenshot from 2022-05-19 14-49-47](https://user-images.githubusercontent.com/17088194/169300379-d6c07dfe-5da9-4984-9fc2-104d846b5541.png)


> * a reasonable magnitude of the tempco of the board (LSB/K)

TODO. That would be for the whole board uniformly?

> * Common mode voltage ripple (or upper limit)

Same problem as with measuring the output ripple. Would you measure this from the load resistor lower side to ground?

**Comment by jordens** [comment]
Cool!

**Comment by jordens** [comment]
If you expect the ripple to be at 500 kHz, shouldn't you choose a horizontal scale in the ~µs/div range instead of ms/div?

**Comment by jordens** [comment]
RC mismatch maybe? how large would the capacitance or resistance mismatch need to be?
Oh. And your stimulus may also be affecting/driving the REF+ channel (finite impedance). Maybe try removing the broken 5k ref resistor and using just that channel (should not need to touch anything else).

**Comment by nkrackow** [comment]
> If you expect the ripple to be at 500 kHz, shouldn't you choose a horizontal scale in the ~µs/div range instead of ms/div?

That was just the timescale where the most noise was apparent. As stated above, the 570 kHz aren't visible in the time domain.

**Comment by nkrackow** [comment]
> RC mismatch maybe? how large would the capacitance or resistance mismatch need to be? Oh. And your stimulus may also be affecting/driving the REF+ channel (finite impedance). Maybe try removing the broken 5k ref resistor and using just that channel (should not need to touch anything else).

Good point, currently trying that.

**Comment by jordens** [comment]
But -90 dB at 50 Hz also sounds good.

**Comment by nkrackow** [comment]
![cmrr_log_long](https://user-images.githubusercontent.com/17088194/169349718-91fb13b8-f04e-4996-a797-40dbb65aef3a.png)
This is on the input channel with the broken 5K that i just removed. 
The other difference is that I changed the offset in the ADC sucht that I could apply +10 mV offset to the differential stimulus, still 10 mV amplitude. 

Now it's even a bit better but still some highpass dynamic going on. Maybe even more gain in the IIR would help to see more but one measurement takes about 20 min..

**Comment by jordens** [comment]
Ah. You used the same stimulus and same IIR gain for both measurements? There is no need for that.
In your figure you are limited by your measurement noise for CM < 10 Hz and both CM and DM > 1 kHz. The data doesn't say much in those regions.
Why not large stimulus (~V) in both cases, and setting the IIR gain so that you get maximum signal (at the DAC) in each case? Then just correct the transfer functions for the difference in gain.
I presume this is still using the DAC and the Analog Disco board or are you just using the ADC samples and RTT?

**Comment by jordens** [comment]
Anyway. This is good enough already. Nothing to worry about.
You can stop now ;)

**Comment by nkrackow** [comment]
> Ah. You used the same stimulus and same IIR gain for both measurements? 

No, like in the first CMRR measurements 2 V offset 1 V amplitude for common mode stimulus. Just the differential stimulus changed to 10 mV offset, 10 mV amplitude.

**Comment by jordens** [comment]
Increasing the IIR coefficient for CMRR is what raises the CM signal out of the output stage quantization, ripple, and measurement noise. Just give it 40-80 dB more gain than DM.
And why was the DM amplitude only 10 mV? Don't you want large amplitude there as well to not be limited?

**Comment by nkrackow** [comment]
> And why was the DM amplitude only 10 mV?

Because that already makes about 0.5 A peak to peak output. I guess I could have increased it by a factor of six but then I'd have to hit exactly mid scale with the offset and that's not much in dB..

**Comment by jordens** [comment]
For DM the gain should be low. Otherwise with low stimulus you'll be limited by the noise of your stimulus.

**Comment by jordens** [comment]
Shows 50 dB more cmrr above 10 kHz. Bow you are only limited by SNR for DM. Anyway. Goot enough. Let's move on.

**Comment by nkrackow** [comment]
Not sure about the meaningfulness of the data above 2-3 kHz. Even with less gain for DM I'd still have to counter the ADC filter roll-off. I guess you might see the high-pass trend continue to a bit higher up then.

**Comment by nkrackow** [comment]
Not sure about the meaningfulness of the data above 2-3 kHz. Even with less gain for DM I'd still have to counter the ADC filter roll-off. I guess you might see the high-pass trend continue to a bit higher up then.

**Comment by jordens** [comment]
Exactly. That's what you want to see, not the noise floor of your Stimulus.

**Comment by jordens** [comment]
@nkrackow it would be great to summarize the measurements in numbers in the style of a datasheet where possible.
AFAICT a couple take home messages already:

* Limited by ADC white noise from 10 mHz to > 250 Hz
* Beats the legacy Thermostat in white noise and latency significantly (legacy: 3.1 LSB rms @ 27 ODR, this: 10 LSB rms @ 1007 ODR) even without the 50 Hz notches.
* CMRR > 100 dB for f <= 50 Hz
* ...

**Comment by jordens** [comment]
nothing to be done here
