### ISSUE TITLE
Remove LED setting and decide on LED indications.

### ISSUE THREAD

**Issue by nkrackow** [quartiq/thermostat-eem#57]
Currently there is still an LED setting in miniconf to turn one LED off and on. That's not a real use and should go.

We could use one set of 4 LEDs to indicate if an output channel is turned on?

**Comment by jordens** [comment]
Sounds good.

Later it would be very useful to have an LED indicate that the TEC channel IIR is within range (i.e. either within its max/min output limits or even some tighter limits on the input).

Maybe also file an issue on the hardware to make 4 of the LEDs red.
