### ISSUE TITLE
Lock `miniconf-mqtt` python utilities to a tag

### ISSUE THREAD

**Issue by ryan-summers** [quartiq/thermostat-eem#86]
See https://github.com/quartiq/stabilizer/issues/661

**Comment by nkrackow** [comment]
Happened in c85251b284125221bae20aa556281f42ab25f433

**Comment by jordens** [comment]
As in stabilizer:
* [x] Use explicit tag/revision dependency
* [ ] Ensure cargo/setup.py comment on keeping python dependency and rust create dependency synchronized is present.

**Comment by jordens** [comment]
[e0a9267](https://github.com/quartiq/thermostat-eem/commit/e0a926764c3336f3e980512242caf1fb8e7e470b)
