### ISSUE TITLE
MCO1 can only be fed by quadrature of PLL1

### ISSUE THREAD

**Issue by SingularitySurfer** [quartiq/thermostat-eem#9]
Currently not sure weather this is a problem or not.

**Comment by SingularitySurfer** [comment]
RCC setup:
![Screenshot from 2022-03-04 18-13-39](https://user-images.githubusercontent.com/17088194/156810534-dd1471f7-2a19-43ea-b288-f7b56f074c2e.png)
Only thing I'm currently not sure yet is th SPI clock source.

**Comment by jordens** [comment]
PER_CK should be fine, no?
No need to add more flexibility than needed here.

**Comment by SingularitySurfer** [comment]
Yes I mean't that I'm not sure what my code actually configures. Oh and I forgot to mention that there must be a bug in CubeMX because I cannot select /1 for DIVP1 even though that is in fact selected and permitted according to the manual. I selected /2 here and put DIVM1 on /2 instead of the /4 it is in my code.

**Comment by jordens** [comment]
@SingularitySurfer is this still a problem or relevant?

**Comment by SingularitySurfer** [comment]
No, the MCO is fed by PER_CK and the output is configured and measured at 2MHz.
